name: BuildBattleGeant
version: '${project.version}'
main: fr.vibe.buildbattlegeant.Main
api-version: 1.19
authors: [Vibe]
description: BuildBattle event plugin
commands:
  regles:
    description: Règles du Build Battle Géant
    usage: /<command>